language: elixir

sudo: false

elixir:
  - 1.8.1

otp_release:
  - 20.3
  - 21.3

env:
  global:
    - MIX_ENV=test

script:
  - mix credo --strict
  - mix dialyzer --halt-exit-status
  - mix test

cache:
  directories:
    - _build
    - deps
    - priv/plts

notifications:
  recipients:
    - asongala@163.com
